"""Fixed MapEngine configuration values."""

FOCUSED_MAP_BUDGET_TOKENS = 4_096
BROAD_MAP_BUDGET_TOKENS = 8_192

SELECTOR_CATALOG_MAX_TOKENS = 4_096
SELECTOR_CATALOG_MAX_FILES = 200
SELECTOR_CATALOG_MAX_DEFS_PER_FILE = 20

MAP_ENGINE_SCHEMA_VERSION = "mapcode.map-engine.v1"
PARSER_VERSION = "mapcode-python-tags-v1"
QUERY_VERSION = "mapcode-python-query-v1"
RANKING_POLICY_VERSION = "mapcode-pagerank-v1"

PAGERANK_ALPHA = 0.85
PAGERANK_MAX_ITER = 100
PAGERANK_TOL = 1e-6

IDENT_BOOST = 10.0
STRUCTURED_IDENT_BOOST = 10.0
PRIVATE_IDENT_PENALTY = 0.1
COMMON_IDENT_PENALTY = 0.1
COMMON_IDENT_DEFINER_THRESHOLD = 5
STRUCTURED_IDENT_MIN_LENGTH = 8
FOCUS_OUTBOUND_BOOST = 50.0
TOP_RANKED_FILES_LIMIT = 5
